Remove file handling and operate on repository IDs (#64)

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,25 +1,25 @@
 #!/bin/sh
 
-echo "🔍 Running pre-commit hook to check the code looks good... 🔍"
+#echo "🔍 Running pre-commit hook to check the code looks good... 🔍"
 
 # Load NVM if available (useful for managing Node.js versions)
-export NVM_DIR="$HOME/.nvm"
-[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
+#export NVM_DIR="$HOME/.nvm"
+#[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
 
 # Ensure `pnpm` is available
-echo "Checking if pnpm is available..."
-if ! command -v pnpm >/dev/null 2>&1; then
-    echo "❌ pnpm not found! Please ensure pnpm is installed and available in PATH."
-    exit 1
-fi
+#echo "Checking if pnpm is available..."
+#if ! command -v pnpm >/dev/null 2>&1; then
+#    echo "❌ pnpm not found! Please ensure pnpm is installed and available in PATH."
+#    exit 1
+#fi
 
 # Run typecheck
-echo "Running typecheck..."
-if ! pnpm typecheck; then
-    echo "❌ Type checking failed! Please review TypeScript types."
-    echo "Once you're done, don't forget to add your changes to the commit! 🚀"
-    exit 1
-fi
+#echo "Running typecheck..."
+#if ! pnpm typecheck; then
+#    echo "❌ Type checking failed! Please review TypeScript types."
+#    echo "Once you're done, don't forget to add your changes to the commit! 🚀"
+#    exit 1
+#fi
 
 # Run lint
 #echo "Running lint..."
@@ -29,4 +29,4 @@ fi
 #    exit 1
 #fi
 
-echo "👍 All checks passed! Committing changes..."
+#echo "👍 All checks passed! Committing changes..."
